/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import UserInterface.ManageAirlines.ManageFlightWorkAreaJPanel;
import business.Airlines;
import business.Airplane;
import business.Flight;
import business.Person;
import business.Seat;
import business.TravelAgency;
import business.TravelOffice;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal Sekhar
 */
public class BookCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookCustomersJPanel
     */
    private Airplane airplane;
    private Airlines airlines;
    private Flight flight;
    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    private Seat s;
    public BookCustomersJPanel(JPanel userProcessContainer, TravelAgency travelAgency,Flight flight, Airplane airplane, Airlines airlines1) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.travelAgency=travelAgency;
        this.flight=flight;
        this.airplane=airplane;
        this.airlines=airlines1;
        s = new Seat();
        
        lblAirliner.setText(airlines.getName());
        lblDepartureTime.setText(flight.getFlightId());
        lblDestination.setText(flight.getDestination());
        lblSource.setText(flight.getSource());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblAirliner = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBookFlight = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtFieldFirstName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtFieldLastName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFieldPhnNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFieldAge = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFieldAddress = new javax.swing.JTextField();
        lblDepartureTime = new javax.swing.JLabel();
        rdBtnWindow = new javax.swing.JRadioButton();
        rdBtnMiddle = new javax.swing.JRadioButton();
        rdBtnAisle = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtFieldDisplayPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Airliner:");

        lblAirliner.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAirliner.setText("Emirates");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Source: ");

        lblSource.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSource.setText("Boston");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Destination:");

        lblDestination.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDestination.setText("Dubai");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Departure Time:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Customer Details");

        btnBookFlight.setText("Book the flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        jLabel10.setText("First Name:");

        txtFieldFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldFirstNameKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Book Flight for the Customer");

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel14.setText("Last Name:");

        txtFieldLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldLastNameKeyPressed(evt);
            }
        });

        jLabel15.setText("Phone Number:");

        txtFieldPhnNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldPhnNumberKeyPressed(evt);
            }
        });

        jLabel16.setText("Age:");

        txtFieldAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldAgeKeyPressed(evt);
            }
        });

        jLabel17.setText("Address:");

        lblDepartureTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDepartureTime.setText("10/08/2017");

        buttonGroup1.add(rdBtnWindow);
        rdBtnWindow.setText("Window");
        rdBtnWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnWindowActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBtnMiddle);
        rdBtnMiddle.setText("Middle");
        rdBtnMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMiddleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBtnAisle);
        rdBtnAisle.setText("Aisle");
        rdBtnAisle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnAisleActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Seat Type:");

        txtFieldDisplayPrice.setEditable(false);
        txtFieldDisplayPrice.setEnabled(false);

        jLabel4.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(16, 16, 16)
                                .addComponent(rdBtnWindow)
                                .addGap(18, 18, 18)
                                .addComponent(rdBtnMiddle)
                                .addGap(54, 54, 54)
                                .addComponent(rdBtnAisle))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(23, 23, 23)
                                    .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(23, 23, 23)
                                    .addComponent(txtFieldPhnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(23, 23, 23)
                                    .addComponent(txtFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(23, 23, 23))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(71, 71, 71)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFieldDisplayPrice)
                                        .addComponent(txtFieldAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(245, 245, 245)
                                .addComponent(btnBookFlight))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAirliner)
                            .addComponent(lblSource)
                            .addComponent(lblDestination)
                            .addComponent(lblDepartureTime))))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAirliner))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSource))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDestination))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDepartureTime))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(txtFieldPhnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(txtFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel17))
                            .addComponent(txtFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnWindow)
                            .addComponent(rdBtnMiddle)
                            .addComponent(rdBtnAisle)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addComponent(txtFieldDisplayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookFlight)
                    .addComponent(btnBack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        try{
           
        String firstName = txtFieldFirstName.getText();
        String lastName = txtFieldLastName.getText();
        String address = txtFieldAddress.getText();
        long phoneNum = Long.parseLong(txtFieldPhnNumber.getText());
        int age = Integer.parseInt(txtFieldAge.getText());
        
        
            
           Person person = travelAgency.getCustomerDirectory().addPerson();
           person.setFirstname(firstName);
           person.setLastName(lastName);
           person.setAddress(address);
           person.setAge(age);
           person.setPhoneNum(phoneNum);
           
           
           if(flight.getSeat().size()==150){
               
               JOptionPane.showMessageDialog(null, "Seats are Full");
           }
           else {
               
               
           
            String seatType;
           if(rdBtnWindow.isSelected()){
               
               seatType = "W";
           }
           else if(rdBtnMiddle.isSelected()){
               
               seatType ="M";
           }
           else if(rdBtnAisle.isSelected()) {
               
               seatType ="A";
           }
           else {
               
               throw new Exception();
           }
           
           Seat seat = flight.addSeat();
           seat.setPerson(person);
           seat.setTypeOfSeat(seatType);
           
           }
        
        
        txtFieldAddress.setText("");
        txtFieldAge.setText("");
        txtFieldFirstName.setText("");
        txtFieldLastName.setText("");
        txtFieldPhnNumber.setText("");
        
        
        JOptionPane.showMessageDialog(null, "Seat Booked Successfully");
        

        
        
        }
        catch(NumberFormatException ne){
            
            JOptionPane.showMessageDialog(null, "Enter integer values for phone Number");
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Please select the Type of seat");
        }
        
        
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void rdBtnWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnWindowActionPerformed
        // TODO add your handling code here:
        
           
               
            s.setTypeOfSeat("W");
            double ratio = s.getRatio();
            double price = ((flight.getPrice())*ratio);
            
            txtFieldDisplayPrice.setText(Double.toString(price));
        
        
    }//GEN-LAST:event_rdBtnWindowActionPerformed

    private void rdBtnMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMiddleActionPerformed
        // TODO add your handling code here:
        
            s.setTypeOfSeat("M");
            double ratio = s.getRatio();
            double price = ((flight.getPrice())*ratio);
            
            txtFieldDisplayPrice.setText(Double.toString(price));
    }//GEN-LAST:event_rdBtnMiddleActionPerformed

    private void rdBtnAisleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnAisleActionPerformed
        // TODO add your handling code here:
        
            s.setTypeOfSeat("A");
            double ratio = s.getRatio();
            double price = ((flight.getPrice())*ratio);
            
            txtFieldDisplayPrice.setText(Double.toString(price));
        
    }//GEN-LAST:event_rdBtnAisleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewBestFlightDealsJPanel viewBestFlightDealsJPanel = (ViewBestFlightDealsJPanel) component;
        viewBestFlightDealsJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFieldFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldFirstNameKeyPressed
        // TODO add your handling code here:
        
     /* char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid First Name");
          txtFieldFirstName.setText("");
      }*/
    }//GEN-LAST:event_txtFieldFirstNameKeyPressed

    private void txtFieldLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldLastNameKeyPressed
        // TODO add your handling code here:
        
     /* char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Last Name");
          txtFieldLastName.setText("");
      }*/
    }//GEN-LAST:event_txtFieldLastNameKeyPressed

    private void txtFieldPhnNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldPhnNumberKeyPressed
        // TODO add your handling code here:
        
     /* char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Numbers");
          txtFieldPhnNumber.setText("");
      }*/
    }//GEN-LAST:event_txtFieldPhnNumberKeyPressed

    private void txtFieldAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldAgeKeyPressed
        // TODO add your handling code here:
        
      /*char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Numbers");
          txtFieldAge.setText("");
      }*/
    }//GEN-LAST:event_txtFieldAgeKeyPressed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookFlight;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAirliner;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblSource;
    private javax.swing.JRadioButton rdBtnAisle;
    private javax.swing.JRadioButton rdBtnMiddle;
    private javax.swing.JRadioButton rdBtnWindow;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldAge;
    private javax.swing.JTextField txtFieldDisplayPrice;
    private javax.swing.JTextField txtFieldFirstName;
    private javax.swing.JTextField txtFieldLastName;
    private javax.swing.JTextField txtFieldPhnNumber;
    // End of variables declaration//GEN-END:variables
}
