/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import business.Airlines;
import business.Airplane;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal Sekhar
 */
public class AddFlightsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFlightsJPanel
     */
    
    private Airlines airlines;
    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    public AddFlightsJPanel(JPanel userProcessContainer, Airlines airlines, TravelAgency travelAgency) {
        initComponents();
        this.airlines=airlines;
        this.userProcessContainer=userProcessContainer;
        this.travelAgency=travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFieldSerialNum = new javax.swing.JTextField();
        txtFieldManufacturer = new javax.swing.JTextField();
        txtFieldModelNumber = new javax.swing.JTextField();
        txtFieldManufacturedYear = new javax.swing.JTextField();
        txtFieldAirlinerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Airplane");

        jLabel2.setText("Model Number:");

        jLabel3.setText("Serial Number:");

        jLabel4.setText("Manufacturer:");

        jLabel5.setText("Manufactured Year:");

        txtFieldManufacturer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldManufacturerKeyPressed(evt);
            }
        });

        txtFieldManufacturedYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldManufacturedYearKeyPressed(evt);
            }
        });

        txtFieldAirlinerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldAirlinerNameKeyPressed(evt);
            }
        });

        jLabel6.setText("Airliner Name:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5)))
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFieldModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFieldManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFieldManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFieldAirlinerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFieldManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnBack))
                .addGap(179, 179, 179))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String modelNum = txtFieldModelNumber.getText();
            String serialNum = txtFieldSerialNum.getText();
            String manufacturer = txtFieldManufacturer.getText();
            int manuYear = Integer.parseInt(txtFieldManufacturedYear.getText());
            String airlinerName = txtFieldAirlinerName.getText();
            
            if(modelNum.equals("")||serialNum.equals("")||manufacturer.equals("")||(txtFieldManufacturedYear.getText()).equals("")||airlinerName.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please add all the values");
            }
            else{
            Airplane airplane = airlines.getAirplaneFleet().addAirplane();
            airplane.setAirlinerName(airlinerName);
            airplane.setManufacturer(manufacturer);
            airplane.setManufacturerYear(manuYear);
            airplane.setModelNum(modelNum);
            airplane.setSerialNum(serialNum);
            
            JOptionPane.showMessageDialog(null, "Airplane Added Successfully");
            
            txtFieldAirlinerName.setText("");
            txtFieldManufacturedYear.setText("");
            txtFieldManufacturer.setText("");
            txtFieldModelNumber.setText("");
            txtFieldSerialNum.setText("");
            }
        }
        catch(NumberFormatException ne){
            
            JOptionPane.showMessageDialog(null, "Enter Year for Manufactured Year");
        }
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFieldManufacturedYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldManufacturedYearKeyPressed
        // TODO add your handling code here:
        
       /* char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Numbers");
          txtFieldManufacturedYear.setText("");
      }*/
    
    }//GEN-LAST:event_txtFieldManufacturedYearKeyPressed

    private void txtFieldAirlinerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldAirlinerNameKeyPressed
        // TODO add your handling code here:
        
      /*char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Airline Name");
          txtFieldAirlinerName.setText("");
      }*/
    }//GEN-LAST:event_txtFieldAirlinerNameKeyPressed

    private void txtFieldManufacturerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldManufacturerKeyPressed
        // TODO add your handling code here:
        
    /*  char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Manufacturer Name");
          txtFieldManufacturer.setText("");
      }*/
    }//GEN-LAST:event_txtFieldManufacturerKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFieldAirlinerName;
    private javax.swing.JTextField txtFieldManufacturedYear;
    private javax.swing.JTextField txtFieldManufacturer;
    private javax.swing.JTextField txtFieldModelNumber;
    private javax.swing.JTextField txtFieldSerialNum;
    // End of variables declaration//GEN-END:variables
}
