/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import business.Airlines;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal Sekhar
 */
public class CreateNewAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirliners
     */
    
    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    private Airlines airlines;
    public CreateNewAirlinersJPanel(JPanel userProcessContainer,TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency=travelAgency;
        airlines = new Airlines();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldAirlinerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldCountry = new javax.swing.JTextField();
        btnCreateAirliner = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddFlights = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Create New Airliners");

        jLabel2.setText("Airliners Name:");

        txtFieldAirlinerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAirlinerNameActionPerformed(evt);
            }
        });
        txtFieldAirlinerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldAirlinerNameKeyPressed(evt);
            }
        });

        jLabel3.setText("Country:");

        txtFieldCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldCountryKeyPressed(evt);
            }
        });

        btnCreateAirliner.setText("Create Airliners");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddFlights.setText("Add Flights");
        btnAddFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnBack)
                        .addGap(166, 166, 166)
                        .addComponent(btnAddFlights))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnCreateAirliner)))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFieldAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(txtFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(btnCreateAirliner)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnAddFlights)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinersWorkAreaJPanel manageAirlinersWorkAreaJPanel = (ManageAirlinersWorkAreaJPanel) component;
        manageAirlinersWorkAreaJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        
        String airlinerName = txtFieldAirlinerName.getText();
        String country = txtFieldCountry.getText();
        
        if((airlinerName.equals("") || country.equals(""))){
            
            JOptionPane.showMessageDialog(null, "Please enter values");
        }
        else{
            
         
         airlines = travelAgency.getAirlineDirectory().addAirline();
        
        airlines.setCountry(country);
        airlines.setName(airlinerName);
        JOptionPane.showMessageDialog(null, "Airliner added Successfully. Add flights for the Airliner");
        
        txtFieldAirlinerName.setText("");
        txtFieldCountry.setText("");
        }
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void txtFieldAirlinerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAirlinerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAirlinerNameActionPerformed

    private void btnAddFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightsActionPerformed
        // TODO add your handling code here:
        
        AddFlightsJPanel panel = new AddFlightsJPanel(userProcessContainer,airlines,travelAgency);
        userProcessContainer.add("AddFlightsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnAddFlightsActionPerformed

    private void txtFieldAirlinerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldAirlinerNameKeyPressed
       
    }//GEN-LAST:event_txtFieldAirlinerNameKeyPressed

    private void txtFieldCountryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldCountryKeyPressed
   
        
        
    }//GEN-LAST:event_txtFieldCountryKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlights;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFieldAirlinerName;
    private javax.swing.JTextField txtFieldCountry;
    // End of variables declaration//GEN-END:variables
}
