/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import business.Airplane;
import business.Flight;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class CreateNewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewFlightJPanel
     */
    private JPanel userProcessContainer;
    private Airplane airplane;
    private TravelAgency travelAgency;

    public CreateNewFlightJPanel(JPanel userProcessContainer, Airplane airplane, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.airplane=airplane;
        this.travelAgency=travelAgency;
        lblAirlinerName.setText(airplane.getAirlinerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAirlinerName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldFlightId = new javax.swing.JTextField();
        btnCreateNewFlights = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFieldSource = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFieldDestination = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFieldDepartureTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFieldBaseFare = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Create New Flights");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Airliners:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lblAirlinerName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAirlinerName.setText("Emirates");
        add(lblAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel4.setText("Flight ID:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtFieldFlightId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFlightIdActionPerformed(evt);
            }
        });
        add(txtFieldFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 140, 30));

        btnCreateNewFlights.setText("Create New Flights");
        btnCreateNewFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewFlightsActionPerformed(evt);
            }
        });
        add(btnCreateNewFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel6.setText("Source:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        txtFieldSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldSourceKeyPressed(evt);
            }
        });
        add(txtFieldSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 30));

        jLabel7.setText("Destination:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtFieldDestination.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldDestinationKeyPressed(evt);
            }
        });
        add(txtFieldDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 30));

        jLabel8.setText("Departure Time:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        add(txtFieldDepartureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 140, 30));

        jLabel9.setText("Base Fare:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        txtFieldBaseFare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldBaseFareKeyPressed(evt);
            }
        });
        add(txtFieldBaseFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightWorkAreaJPanel manageFlightWorkAreaJPanel = (ManageFlightWorkAreaJPanel) component;
         manageFlightWorkAreaJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateNewFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewFlightsActionPerformed
        // TODO add your handling code here:
        try{
            
        String flightId = txtFieldFlightId.getText();
        String source = txtFieldSource.getText();
        String destination = txtFieldDestination.getText();
        int baseFare = Integer.parseInt(txtFieldBaseFare.getText());
            SimpleDateFormat DateFormat = new SimpleDateFormat("MM/dd/yyyy hh:mm:ss");
        Date departureTime = DateFormat.parse(txtFieldDepartureTime.getText());
        
        Flight flight = airplane.addFlight();
        flight.setFlightId(flightId);
        flight.setDepartureTime(departureTime);
        flight.setDestination(destination);
        flight.setSource(source);
        flight.setPrice(baseFare);
        
        flight = travelAgency.getMs().getFs().addFlight();
        flight.setFlightId(flightId);
        flight.setDepartureTime(departureTime);
        flight.setDestination(destination);
        flight.setSource(source);
        flight.setPrice(baseFare);
        JOptionPane.showMessageDialog(null, "Flight Added Successfully");
      
        txtFieldBaseFare.setText("");
        txtFieldDepartureTime.setText("");
        txtFieldDestination.setText("");
        txtFieldFlightId.setText("");
        txtFieldSource.setText(""); 
        
        }
        catch(NumberFormatException ne){
            
         JOptionPane.showMessageDialog(null, "Please enter Integer for Base Fare");
            
        }
        catch(ParseException pe){
            
            JOptionPane.showMessageDialog(null, "Enter Date in the given format MM/dd/yyyy hh:mm:ss");
        }
    }//GEN-LAST:event_btnCreateNewFlightsActionPerformed

    private void txtFieldSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSourceKeyPressed
        // TODO add your handling code here:
        
      char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Source Name");
          txtFieldSource.setText("");
      }
    }//GEN-LAST:event_txtFieldSourceKeyPressed

    private void txtFieldDestinationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldDestinationKeyPressed
        // TODO add your handling code here:
        
      /* char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Destination Name");
          txtFieldDestination.setText("");
      }*/
    }//GEN-LAST:event_txtFieldDestinationKeyPressed

    private void txtFieldBaseFareKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldBaseFareKeyPressed
        // TODO add your handling code here:
        
    /*  char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Numbers");
          txtFieldBaseFare.setText("");
      }*/
        
    }//GEN-LAST:event_txtFieldBaseFareKeyPressed

    private void txtFieldFlightIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFlightIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFlightIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewFlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JTextField txtFieldBaseFare;
    private javax.swing.JTextField txtFieldDepartureTime;
    private javax.swing.JTextField txtFieldDestination;
    private javax.swing.JTextField txtFieldFlightId;
    private javax.swing.JTextField txtFieldSource;
    // End of variables declaration//GEN-END:variables
}
