/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import business.Airlines;
import business.Airplane;
import business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal Sekhar
 */
public class ManageAirlinersWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliners
     */
    private Airlines airlines;
    
    private TravelAgency travelAgency;
    private JPanel userProcessContainer;
    public ManageAirlinersWorkAreaJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.travelAgency=travelAgency;
        Airlines  airlines=new Airlines();
//        populateTable();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateNewAirliners = new javax.swing.JButton();
        btnSearchAirliners = new javax.swing.JButton();
        scrollPaneSeachAirliners = new javax.swing.JScrollPane();
        tblAllAirliners = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        scrollPaneAllAirliners = new javax.swing.JScrollPane();
        tblSearchedAirliners = new javax.swing.JTable();
        txtFieldAirliners = new javax.swing.JTextField();
        txtFieldCountry = new javax.swing.JTextField();
        btnselect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnMngFlights = new javax.swing.JButton();
        txtFieldSearchFlights = new javax.swing.JTextField();
        btnViewAllFlights = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateNewAirliners.setText("Create New Airliners");
        btnCreateNewAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewAirlinersActionPerformed(evt);
            }
        });
        add(btnCreateNewAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 180, -1));

        btnSearchAirliners.setText("Search Airliners");
        btnSearchAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAirlinersActionPerformed(evt);
            }
        });
        add(btnSearchAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 135, -1));

        tblAllAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Country", "Number of Flights"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneSeachAirliners.setViewportView(tblAllAirliners);
        if (tblAllAirliners.getColumnModel().getColumnCount() > 0) {
            tblAllAirliners.getColumnModel().getColumn(0).setResizable(false);
            tblAllAirliners.getColumnModel().getColumn(1).setResizable(false);
            tblAllAirliners.getColumnModel().getColumn(2).setResizable(false);
        }

        add(scrollPaneSeachAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 520, 420, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Search Airliners");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        tblSearchedAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneAllAirliners.setViewportView(tblSearchedAirliners);
        if (tblSearchedAirliners.getColumnModel().getColumnCount() > 0) {
            tblSearchedAirliners.getColumnModel().getColumn(0).setResizable(false);
            tblSearchedAirliners.getColumnModel().getColumn(1).setResizable(false);
        }

        add(scrollPaneAllAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 97));

        txtFieldAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAirlinersActionPerformed(evt);
            }
        });
        add(txtFieldAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, -1));
        add(txtFieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 120, -1));

        btnselect.setText("select");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });
        add(btnselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jLabel2.setText("Airliners");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 53, -1));

        jLabel3.setText("Country");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Manage Airliners");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("All Airliners");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        btnMngFlights.setText("Manage Flights");
        btnMngFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngFlightsActionPerformed(evt);
            }
        });
        add(btnMngFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, -1, -1));
        add(txtFieldSearchFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 120, -1));

        btnViewAllFlights.setText("View All Flights");
        btnViewAllFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllFlightsActionPerformed(evt);
            }
        });
        add(btnViewAllFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 140, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable2(){
        
                
        DefaultTableModel dtm = (DefaultTableModel)tblAllAirliners.getModel();
        dtm.setRowCount(0);
        String AirlinesName = txtFieldSearchFlights.getText();
        
        for(Airlines airlines : travelAgency.getAirlineDirectory().getAirlinesList()){
        
        if (airlines.getName().equalsIgnoreCase(AirlinesName)){
            
            //for(Airplane airplane : airlines.getAirplaneFleet().getAirplaneFleet()){
                
            Object row[] = new Object[3];
            row[0] = airlines;
            row[1] = airlines.getCountry();
            row[2] = travelAgency.numberOfFlights(txtFieldSearchFlights.getText());
            
            dtm.addRow(row);
                
                
            //}
        }
        
        }
        
    }
    
    private void btnSearchAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAirlinersActionPerformed
        // TODO add your handling code here:
        

        populateTable2();
        
    }//GEN-LAST:event_btnSearchAirlinersActionPerformed

    private void btnCreateNewAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewAirlinersActionPerformed
        // TODO add your handling code here:
        
        
        CreateNewAirlinersJPanel panel = new CreateNewAirlinersJPanel(userProcessContainer,travelAgency);
        userProcessContainer.add("CreateNewAirlinersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCreateNewAirlinersActionPerformed

    private void btnMngFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngFlightsActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = tblAllAirliners.getSelectedRow();
        
        if(selectedrow <0)
        {
            JOptionPane.showMessageDialog(null, "Please select a Row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        else {
            
        airlines = (Airlines) tblAllAirliners.getValueAt(selectedrow, 0);
        ManageFlightWorkAreaJPanel panel = new ManageFlightWorkAreaJPanel(userProcessContainer,airlines,travelAgency);
        userProcessContainer.add("ManageFlightWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_btnMngFlightsActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblSearchedAirliners.getSelectedRow();
        
        if(selectedrow <0)
        {
            JOptionPane.showMessageDialog(null, "Please select a Row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        else {
        
        txtFieldAirliners.setEnabled(true);
        txtFieldCountry.setEnabled(true);
        
        airlines = (Airlines) tblSearchedAirliners.getValueAt(selectedrow, 0);    
        txtFieldAirliners.setText(airlines.getName());
        txtFieldCountry.setText(airlines.getCountry());

            
        }
        
    }//GEN-LAST:event_btnselectActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
       String AirlineName = txtFieldAirliners.getText();
       String AirlineCountry = txtFieldCountry.getText();
       
       airlines.setCountry(AirlineCountry);
       airlines.setName(AirlineName);
        populateTable();
        txtFieldAirliners.setText("");
        txtFieldCountry.setText("");
        txtFieldAirliners.setEnabled(false);
        txtFieldCountry.setEnabled(false);
        
       JOptionPane.showMessageDialog(null, "Airliner Updated Successfully");

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewAllFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllFlightsActionPerformed
        // TODO add your handling code here:
        
        
        ViewAllFlights panel = new ViewAllFlights(userProcessContainer,travelAgency);
        userProcessContainer.add("ViewAllFlights", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnViewAllFlightsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = tblSearchedAirliners.getSelectedRow();

        if(selectedrow >=0)
        {
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the details","Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION){
                
                Airlines airlines = (Airlines) tblSearchedAirliners.getValueAt(selectedrow, 0);
                
                travelAgency.getAirlineDirectory().deleteAirline(airlines);
                populateTable();
                
            }
        }
        else {
            
            JOptionPane.showMessageDialog(null, "Please select a Row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtFieldAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAirlinersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAirlinersActionPerformed

    
        public void populateTable(){
            //System.out.println("hi"+travelAgency.getAirlineDirectory().getAirlinesList().size());
        DefaultTableModel dtm = (DefaultTableModel)tblSearchedAirliners.getModel();
        dtm.setRowCount(0);
        
        for( Airlines airlines : travelAgency.getAirlineDirectory().getAirlinesList())
        {
            Object row[] = new Object[2];
            row[0] = airlines;
            row[1] = airlines.getCountry();
            
            dtm.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewAirliners;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMngFlights;
    private javax.swing.JButton btnSearchAirliners;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAllFlights;
    private javax.swing.JButton btnselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane scrollPaneAllAirliners;
    private javax.swing.JScrollPane scrollPaneSeachAirliners;
    private javax.swing.JTable tblAllAirliners;
    private javax.swing.JTable tblSearchedAirliners;
    private javax.swing.JTextField txtFieldAirliners;
    private javax.swing.JTextField txtFieldCountry;
    private javax.swing.JTextField txtFieldSearchFlights;
    // End of variables declaration//GEN-END:variables
}
