/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import business.Airlines;
import business.Airplane;
import business.Flight;
import business.TravelAgency;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal Sekhar
 */
public class ViewAllFlights extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllFlights
     */
    private TravelAgency travelAgency;
    private JPanel userProcessContainer;
    public ViewAllFlights(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.travelAgency=travelAgency;
        this.userProcessContainer=userProcessContainer;
        populateTable();
        
    }
        public void populateTable(){
          
        DefaultTableModel dtm = (DefaultTableModel)tblViewFlights.getModel();
        dtm.setRowCount(0);
        
        for( Airlines airlines : travelAgency.getAirlineDirectory().getAirlinesList()){
        {
            for(Airplane airplane : airlines.getAirplaneFleet().getAirplaneFleet()){
                
                for(Flight flight : airplane.getFlight()){
                
            
            Object row[] = new Object[7];
            row[0] = flight;
            row[2] = flight.getDestination();
            row[1] = flight.getSource();
            row[3] = flight.getDepartureTime();
            row[4] = flight.getPrice();
            row[5] = airplane;
            row[6] = airplane.getAirlinerName();
            dtm.addRow(row);
        }
        }    
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneViewFlights = new javax.swing.JScrollPane();
        tblViewFlights = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Source", "Destination", "Departure Time", "Base Price", "Serial Number", "Airliner Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneViewFlights.setViewportView(tblViewFlights);
        if (tblViewFlights.getColumnModel().getColumnCount() > 0) {
            tblViewFlights.getColumnModel().getColumn(1).setResizable(false);
            tblViewFlights.getColumnModel().getColumn(2).setResizable(false);
            tblViewFlights.getColumnModel().getColumn(3).setResizable(false);
            tblViewFlights.getColumnModel().getColumn(4).setResizable(false);
            tblViewFlights.getColumnModel().getColumn(5).setResizable(false);
            tblViewFlights.getColumnModel().getColumn(6).setResizable(false);
        }

        add(scrollPaneViewFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 750, 180));

        jLabel1.setText("View All Flights");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 32, 99, 27));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollPaneViewFlights;
    private javax.swing.JTable tblViewFlights;
    // End of variables declaration//GEN-END:variables
}
