/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import business.Flight;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import business.Airlines;
import java.awt.Component;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ViewFlightsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightsJPanel
     */
    private Airlines airlines1;
    private JPanel userProcessContainer;
    private Flight flight;

    public ViewFlightsJPanel(JPanel userProcessContainer, Flight flight, Airlines airlines1) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.flight = flight;
        this.airlines1=airlines1;
        populateFlightDetails();
        lblAirlinerName.setText(airlines1.getName());
        txtFieldSource.setEnabled(false);
        txtFieldDestination.setEnabled(false);
        txtFieldDepartureTime.setEnabled(false);
        txtFieldFlightID.setEnabled(false);
        txtFieldBasePrice.setEnabled(false);
    }
    
     private void populateFlightDetails()
    {
        
    txtFieldSource.setText(flight.getSource());
    txtFieldDestination.setText(flight.getDestination());
    txtFieldBasePrice.setText(Integer.toString(flight.getPrice()));
    
    SimpleDateFormat Dateformat = new SimpleDateFormat("MM:dd:yyyy hh:mm:ss");
    txtFieldDepartureTime.setText(Dateformat.format(flight.getDepartureTime()));
    txtFieldFlightID.setText(flight.getFlightId());
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAirliner = new javax.swing.JLabel();
        lblAirlinerName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFieldBasePrice = new javax.swing.JTextField();
        txtFieldFlightID = new javax.swing.JTextField();
        txtFieldSource = new javax.swing.JTextField();
        txtFieldDestination = new javax.swing.JTextField();
        txtFieldDepartureTime = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Flights");

        lblAirliner.setText("Airliner:");

        lblAirlinerName.setText("Emirates");

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Flight Id:");

        jLabel5.setText("Source:");

        jLabel6.setText("Destination:");

        jLabel7.setText("Departure Time:");

        jLabel8.setText("Base Price:");

        txtFieldBasePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldBasePriceKeyPressed(evt);
            }
        });

        txtFieldSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldSourceKeyPressed(evt);
            }
        });

        txtFieldDestination.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldDestinationKeyPressed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack)
                        .addGap(73, 73, 73)
                        .addComponent(btnSave)
                        .addGap(71, 71, 71)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAirliner)
                                .addGap(26, 26, 26)
                                .addComponent(lblAirlinerName)))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAirliner)
                    .addComponent(lblAirlinerName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtFieldDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(txtFieldBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate))))
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightWorkAreaJPanel manageFlightWorkAreaJPanel = (ManageFlightWorkAreaJPanel) component;
        manageFlightWorkAreaJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       
       try{
       String flightID = txtFieldFlightID.getText();
       String source = txtFieldSource.getText();
       String destination = txtFieldDestination.getText();
       
       SimpleDateFormat Dateformat = new SimpleDateFormat("MM:dd:yyyy hh:mm:ss");
       Date departureTime = Dateformat.parse(txtFieldDepartureTime.getText());
       int basePrice = Integer.parseInt(txtFieldBasePrice.getText());
       
        flight.setFlightId(flightID);
        flight.setSource(source);
        flight.setDestination(destination);
        flight.setDepartureTime(departureTime);
        flight.setPrice(basePrice);
        //populateTable();
         txtFieldBasePrice.setText("");
         txtFieldDepartureTime.setText("");
         txtFieldDestination.setText("");
         txtFieldFlightID.setText("");
         txtFieldSource.setText("");
         
         JOptionPane.showMessageDialog(null, "Flight Updated Successfully");
       }
       
       catch(ParseException pe){
          
           JOptionPane.showMessageDialog(null, "Please provide the Date in the given format MM:dd:yyyy hh:mm:ss");
           
       }
       catch (NumberFormatException ne){
           
           JOptionPane.showMessageDialog(null, "Please provide integer Value");
       }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        

        txtFieldSource.setEnabled(true);
        txtFieldDestination.setEnabled(true);
        txtFieldDepartureTime.setEnabled(true);
        txtFieldFlightID.setEnabled(true);
        txtFieldBasePrice.setEnabled(true);
        
       

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtFieldSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSourceKeyPressed
        // TODO add your handling code here:
      char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Source Name");
          txtFieldSource.setText("");
      }
        
    }//GEN-LAST:event_txtFieldSourceKeyPressed

    private void txtFieldDestinationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldDestinationKeyPressed
        // TODO add your handling code here:
      char c = evt.getKeyChar();
      if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'z') || (c == evt.VK_CAPS_LOCK) || (c == evt.VK_SPACE)||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Destination Name");
          txtFieldDestination.setText("");
      }
        
    }//GEN-LAST:event_txtFieldDestinationKeyPressed

    private void txtFieldBasePriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldBasePriceKeyPressed
        // TODO add your handling code here:
        
    char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == evt.VK_BACK_SPACE) ||
         (c == evt.VK_DELETE))) {
        
       JOptionPane.showMessageDialog(null, "Enter Valid Numbers");
          txtFieldBasePrice.setText("");
      }
    }//GEN-LAST:event_txtFieldBasePriceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAirliner;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JTextField txtFieldBasePrice;
    private javax.swing.JTextField txtFieldDepartureTime;
    private javax.swing.JTextField txtFieldDestination;
    private javax.swing.JTextField txtFieldFlightID;
    private javax.swing.JTextField txtFieldSource;
    // End of variables declaration//GEN-END:variables
}
